"":
  joint_states_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50
        
  joint1_position_controller:
      type: position_controllers/JointTrajectoryController
      joints:
          - joint1
      gains:
          joint1:  {p: 10, i: 1, d: 1}
  joint2_position_controller:
      type: position_controllers/JointTrajectoryController
      joints:
          - joint2
      gains:
          joint2:  {p: 10, i: 1, d: 1}
  joint3_position_controller:
      type: position_controllers/JointTrajectoryController
      joints:
          - joint3
      gains:
          joint3:  {p: 10, i: 1, d: 1}
  joint4_position_controller:
      type: position_controllers/JointTrajectoryController
      joints:
          - joint4
      gains:
          joint4:  {p: 10, i: 1, d: 1}
  gripper_position_controller:
      type: position_controllers/JointTrajectoryController
      joints:
        - gripper
      gains:
        gripper: {p: 10, i: 1, d: 1}
  gripper_sub_position_controller:
      type: position_controllers/JointTrajectoryController
      joints:
        - gripper_sub
      gains:
        gripper_sub: {p: 10, i: 1, d: 1}
