controller_list:
  - name: fake_arx_mini_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
  - name: fake_arx_mini_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - gripper
initial:  # Define initial robot poses per group
  - group: arx_mini_arm
    pose: home